# Generated by Django 6.0.2 on 2026-03-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_reply_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='api.country'),
        ),
    ]
