# Generated by Django 6.0.2 on 2026-03-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='default/default-user.jpg', null=True, upload_to='images/'),
        ),
    ]
