# Generated by Django 6.0.2 on 2026-03-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recipe_cover_image_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportstamp',
            name='note',
        ),
        migrations.RemoveField(
            model_name='passportstamp',
            name='recipe',
        ),
    ]
